name: Docker Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t logger .

    - name: Run Docker Container and Test
      run: |
        mkdir -p logs
        chmod 777 logs
        echo -e "text1\ntext2\ntext3" > input.txt
        docker run -i -v "$(pwd)/logs/:/home/logs/" logger < input.txt

    - name: Check Log Outputs
      run: |
        cat logs/log.txt
