name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential
      
      - name: Configure CMake
        run: cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release
      
      - name: Build
        run: cmake --build _build
      
      - name: Create TGZ package
        run: |
          cd _build
          cpack -G "TGZ"
          cd ..
      
      - name: Upload TGZ artifact
        uses: actions/upload-artifact@v4
        with:
          name: print-package
          path: _build/*.tar.gz
